// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Used only by the Prisma CLI (migrate/studio/db pull), never by the app at
  // runtime. Points at the direct/unpooled connection since DDL statements
  // (migrations) shouldn't go through a connection pooler like Neon's PgBouncer.
  datasource: {
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
